"""
gen_rtl.py - generate the constant-dependent RTL from the golden model:

  rtl/ntt_defs.vh     `NTT_W(scheme) macro (coefficient width, used in port lists)
  rtl/ntt_params.vh   scheme constants (Q, W, layers, Barrett M/K, Montgomery -q^-1, R^-1)
  rtl/ntt_tw_rom.v    forward / inverse twiddle ROMs for every scheme x reduction

Run from the repo root:  python3 model/gen_rtl.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from ntt_model import SCHEMES, Barrett, Montgomery, zetas, inv_twiddles

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RTL = os.path.join(ROOT, "rtl")
ORDER = ["kyber", "dilithium"]          # SCHEME parameter: 0 = kyber, 1 = dilithium
HDR = "// AUTO-GENERATED by model/gen_rtl.py - do not edit by hand.\n"


def sel(values):
    """Nested ternary on SCHEME for a per-scheme integer constant."""
    expr = str(values[-1])
    for i in range(len(values) - 2, -1, -1):
        expr = f"(SCHEME == {i}) ? {values[i]} : {expr}"
    return expr


def gen_params():
    sch = [SCHEMES[n] for n in ORDER]
    rows = {
        "Q": [s.q for s in sch],
        "LAYERS": [s.layers for s in sch],
        "BAR_K": [Barrett(s).k for s in sch],
        "BAR_M": [Barrett(s).m for s in sch],
        "MONT_QN": [Montgomery(s).qneg_inv for s in sch],
        "MONT_RINV": [pow(1 << s.w, -1, s.q) for s in sch],
    }
    lines = [HDR,
             "// Included inside a module that declares `parameter SCHEME`.",
             "// SCHEME: " + ", ".join(f"{i} = {n}" for i, n in enumerate(ORDER)), ""]
    for k, v in rows.items():
        lines.append(f"localparam integer {k:<9} = {sel(v)};")
    with open(os.path.join(RTL, "ntt_params.vh"), "w") as f:
        f.write("\n".join(lines) + "\n")
    # Coefficient width is needed in port lists, so it is a macro rather than a localparam.
    defs = [HDR, "`ifndef NTT_DEFS_VH", "`define NTT_DEFS_VH",
            f"`define NTT_W(s) ({sel([s.w for s in sch]).replace('SCHEME', '(s)')})",
            "`endif", ""]
    with open(os.path.join(RTL, "ntt_defs.vh"), "w") as f:
        f.write("\n".join(defs))


def rom_case(name, table, w):
    out = [f"            always @(*) begin",
           f"                case (idx)"]
    for i, v in enumerate(table):
        out.append(f"                    8'd{i}: {name} = {w}'d{v};")
    out += [f"                    default: {name} = {w}'d0;",
            f"                endcase",
            f"            end"]
    return out


def gen_rom():
    lines = [HDR,
             "// Twiddle ROM. idx = m + (j >> (k+1)) for a layer with butterfly distance 2^k,",
             "// where m = 128 >> k is the number of blocks in that layer.",
             "// Forward table: zeta^brv(idx).  Inverse table: -zeta[2m-1-blk].",
             "// Montgomery builds store every entry pre-multiplied by R = 2^W.",
             "module ntt_tw_rom #(",
             "    parameter SCHEME = 0,   // 0 = kyber, 1 = dilithium",
             "    parameter RED    = 0,   // 0 = barrett, 1 = montgomery",
             "    parameter W      = 12",
             ") (",
             "    input  wire [7:0]   idx,",
             "    input  wire         inv,",
             "    output wire [W-1:0] w",
             ");",
             "    reg [W-1:0] w_fwd, w_inv;",
             "    assign w = inv ? w_inv : w_fwd;",
             "    generate"]
    first = True
    for si, sname in enumerate(ORDER):
        s = SCHEMES[sname]
        for ri, red in enumerate((Barrett(s), Montgomery(s))):
            cond = f"(SCHEME == {si}) && (RED == {ri})"
            lines.append(f"        {'if' if first else 'else if'} ({cond}) begin : g_s{si}_r{ri}")
            first = False
            fwd = [red.twiddle(z) for z in zetas(s)]
            inv = [red.twiddle(z) for z in inv_twiddles(s)]
            lines += rom_case("w_fwd", fwd, s.w)
            lines += rom_case("w_inv", inv, s.w)
            lines.append("        end")
    lines += ["        else begin : g_bad",
              "            initial $display(\"ntt_tw_rom: unsupported SCHEME/RED\");",
              "            always @(*) begin w_fwd = {W{1'b0}}; w_inv = {W{1'b0}}; end",
              "        end",
              "    endgenerate",
              "endmodule", ""]
    with open(os.path.join(RTL, "ntt_tw_rom.v"), "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    os.makedirs(RTL, exist_ok=True)
    gen_params()
    gen_rom()
    print("wrote rtl/ntt_defs.vh, rtl/ntt_params.vh, rtl/ntt_tw_rom.v")
