// AUTO-GENERATED by model/gen_rtl.py - do not edit by hand.

// Included inside a module that declares `parameter SCHEME`.
// SCHEME: 0 = kyber, 1 = dilithium

localparam integer Q         = (SCHEME == 0) ? 3329 : 8380417;
localparam integer LAYERS    = (SCHEME == 0) ? 7 : 8;
localparam integer BAR_K     = (SCHEME == 0) ? 24 : 46;
localparam integer BAR_M     = (SCHEME == 0) ? 5039 : 8396807;
localparam integer MONT_QN   = (SCHEME == 0) ? 3327 : 8380415;
localparam integer MONT_RINV = (SCHEME == 0) ? 2704 : 8372232;
